# This is a document
#
# Printing is in reverse

title = "Some text for title"
fltnum = 3.14
boolval = true
intnum = 42


[sectionA]
aaa = "1"
bbb = "2"
ccc = "3"

[sectionB]
## NB these don't seem to come in a integers
aaa = 1
bbb = 2
ccc = 3

[sectionC]
aaa = 1.1
bbb = 2.2
ccc = 3.3

[sectionD]
foo = [ 1, 2, 3 ]


