# This is a document
#
# Printing is in reverse

title = "Some text for title"
fltnum = 3.14
boolval = true
intnum = 42


[sectionA]
aaa = "1"
bbb = "2"
ccc = "3"

[sectionB]
aaa = "1"
bbb = "2"
ccc = "3"


